import { SpeedInsights } from '@vercel/speed-insights/next';

import Aside from '@/layouts/Aside';
import Body from '@/layouts/Body';
import Header from '@/layouts/Header';
import Main from '@/layouts/Main';

import Categories from '@/components/aside/Categories';
import Home from '@/components/aside/Home';

// TODO: import '@/styles/global.scss';

// TODO: export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <Body>
        <Header />
        <Aside>
          <Home />
          <Categories />
        </Aside>
        <Main>{children}</Main>
        <SpeedInsights />
      </Body>
    </html>
  );
}
