import { SpeedInsights } from '@vercel/speed-insights/next';

import Article from '@/components/layouts/Article';
import Aside from '@/components/layouts/Aside';
import Body from '@/components/layouts/Body';
import Header from '@/components/layouts/Header';
import Main from '@/components/layouts/Main';

import Categories from '@/components/aside/Categories';
import Home from '@/components/aside/Home';

import Title from '@/components/header/Title';

// TODO: import '@/styles/global.scss';

// TODO: export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <Body>
        <Header>
          <Title />
        </Header>
        <Aside>
          <Home />
          <Categories />
        </Aside>
        <Main>
          <Article>{children}</Article>
        </Main>

        <SpeedInsights />
      </Body>
    </html>
  );
}
